spring:
  application:
    name: springAiChat
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama2
          temperature: 0.7

server:
  port: 10001
